[dataP,totalP,tbP,fbP]=...
    sensibilityvpp('C:\Users\qian\Dropbox\stage\Electrophorese\profils\Etude avec Gerard\P\');
%[dataN,totalN,tbN,fbN]=...
  %  sensibilityvpp('C:\Users\qian\Dropbox\stage\Electrophorese\profils\Etude avec Gerard\N\');

